name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          repository: "Indosiasat/vless-Trojan-Shadowshock"
          token: ${{ secrets.noobz }}

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Start Scan
        run: |
          bun install --no-cache && bun run ./helper/proxyip.ts

      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '["./*List.txt", "./*List.json"]'
          default_author: github_actions
          fetch: true
          message: "Update proxy list"
          push: true
